stages:
  - test
  - build

test-java:
  image: maven:3.6.3-openjdk-11
  stage: test
  script:
    - mvn test
  cache:
    paths:
      - .m2/repository
  only:
    - master


build-java:
  image: maven:3.6.3-openjdk-11
  stage: build
  script: mvn clean compile
  cache:
    paths:
      - .m2/repository
  only:
    - master
